
trigger: none
pr: none

# Connect devsecops repository for templates.

resources:
  repositories:
    - repository: 'Templates'
      name: 'udayprakash1997'
      type: github
      ref: main
      endpoint: Unity

# Build Stage
stages:
- stage: 'MainStage'
  displayName: "Build and Push"
  jobs:
  - job: Build
    displayName: Build & Deploy
    pool:
     vmImage: ubuntu-latest
    steps:

      - checkout: self
    # Building Docker Image
      - template: DockerBuild.yml@Templates
        parameters:
          ProjectName: 'dotnet-project'
          ConnectionTypeName: 'foodalert-prakash'
          RegistryServiceConnection: 'Acr-connection'
          WebAppName: 'appservicefoodalerttest11233'
          repository: 'udaycontainer'
          containerRegistry: udaycontainer.azurecr.io
          tag: 'dev-v$(Build.BuildNumber)'
          token: 'false'

